import type { Metadata } from "next";
import * as React from "react";

import { TetrisLabContextProvider } from "@/state/TetrisLabContext";
import getRandomVariant from "@/utils/getRandomVariant";

import { AppProvider, type Navigation } from "@toolpad/core/AppProvider";

import HomeIcon from "@mui/icons-material/Home";
import SportsEsportsIcon from "@mui/icons-material/SportsEsports";
import InfoIcon from "@mui/icons-material/Info";
import SchoolIcon from "@mui/icons-material/School";
import ChatIcon from "@mui/icons-material/Chat";
import DashboardIcon from "@mui/icons-material/Dashboard";

import tetrisLabTheme from "@/app/theme";

import "./normalize.css";
import "./layout.scss";

export const metadata: Metadata = {
  title: "TetrisLab",
  description: "Generated by create next app",
};

export const NAVIGATION: Navigation = [
  {
    segment: "",
    title: "Home",
    icon: <HomeIcon />,
  },
  {
    segment: "game",
    title: "Start Game",
    icon: <SportsEsportsIcon />,
  },
  {
    segment: "about",
    title: "About",
    icon: <InfoIcon />,
  },
  {
    segment: "thesis",
    title: "Thesis (Draft)",
    icon: <SchoolIcon />,
  },
  {
    segment: "feedback",
    title: "Feedback",
    icon: <ChatIcon />,
  },
  {
    segment: "admin",
    title: "Admin",
    icon: <DashboardIcon />,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const randomVariant = getRandomVariant();

  return (
    <html lang="en">
      <body>
        <AppProvider
          branding={{
            logo: <img src="/logoSmall.svg" />,
            title: "TetrisLab",
            homeUrl: "/",
          }}
          navigation={NAVIGATION}
          theme={tetrisLabTheme}
        >
          <TetrisLabContextProvider randomVariant={randomVariant}>
            {children}
          </TetrisLabContextProvider>
        </AppProvider>
      </body>
    </html>
  );
}
